repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--max-line-length=88', '--ignore=E266,E501,W503,F403,F401', '--max-complexity=18']
-   repo: local
    hooks:
    -   id: pre-commit-local
        name: bump
        always_run: true
        entry: ./bump.sh
        language: script
